services:
  db:
    image: mysql:8.0 # Use the official MySQL image
    ports:
      - "3306:3306" # MySQL runs on port 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # Root password for the database
      MYSQL_DATABASE: event_ticket_platform # Create a dedicated database

  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - start-dev
      - --db=dev-file

volumes:
  keycloak_data:
    driver: local
  mysql_data: # Optional: Add a volume to persist MySQL data
    driver: local